### ISSUE TITLE
Request: 3D case

### ISSUE THREAD

**Issue by WhistleMaster** [PricelessToolkit/MailBoxGuard#1]
Hi !

Thanks for the great work ! I've ordered the PCB on your shop and I'm looking for the 3D case. 

Thanks !
Regards,

WM

**Comment by PricelessToolkit** [comment]
Thanks for your support! 🤗  there are the STEP files, I forgot to export them to STL. Today I will upload them too.

**Comment by PricelessToolkit** [comment]
Done!
