### ISSUE TITLE
Request: add SNR

### ISSUE THREAD

**Issue by steuerzentrale** [PricelessToolkit/MailBoxGuard#30]
Hi there

is it possible to add the SNR-value in addition to the RSSI which is already being reported? This would help to determine if the connection is good. At the moment I have an RSSI between -98dbm and -107dbm but I dont know the SNR to evaluate if the connection is good or I should reposition the sensor.

all the best, Andrew

**Comment by PricelessToolkit** [comment]
Mailbox_Guard_Sensor_HARestAPI reporting SNR, but in your place, I wouldn't even worry about SNR.. the best thing you can do is to change the gateway antenna.
