### ISSUE TITLE
PIR Sensitivity + Door contact sensor

### ISSUE THREAD

**Issue by RubenWaterman** [PricelessToolkit/MailBoxGuard#39]
First of all, awesome project and thanks very much! I've got it successfully integrated in my Loxone smart home 🤩
![Screenshot 2024-01-25 at 10 14 17](https://github.com/PricelessToolkit/MailBoxGuard/assets/5938863/6c0ec271-e186-41a7-a811-b0e2f9474b82)

For some reason, the on-board PIR triggers way too often, when there is no mail inserted. Is there a configuration flag to make the PIR less sensitive?

I was also thinking of soldering a door contact on board (and either attach on the slat that opens when mail is inserted to trigger the "new mail" activity, OR to put the door contact on the actual door so that would trigger the "I've seen the mail" event). I found the correct pins for this on the board but I didn't find any code on how to set this up. Do you happen to have an example for this?

**Comment by RubenWaterman** [comment]
Ah, is it possible to trigger two separate types of MQTT messages, i.e. one for PIR activity and one for door contact sensor?

**Comment by WhistleMaster** [comment]
I don't think so. The PIR and the door contact switch are both used as trigger on the board.

**Comment by PricelessToolkit** [comment]
Thank you for supporting my work.
"For some reason, the on-board PIR triggers way too often" If you have a mailbox with a small slit for mail and it stays open, change the location of the sensor so that the sensor faces in the other direction.
