### ISSUE TITLE
Hi,  Andrew LeCody "aceat64"

### ISSUE THREAD

**Issue by PricelessToolkit** [PricelessToolkit/MailBoxGuard#4]
I hope this message reaches you. I wasn't sure how to get in touch, and I find it unfortunate that sending a message through GitHub to a contributor isn't possible. Could you please reach out to me via email? There are a few things I'd like to send to you :) but unfortunately, I don't have your physical address.
Thanks

**Comment by WhistleMaster** [comment]
I guess you could write a comment in PR #3 so that it will get your message :)

**Comment by PricelessToolkit** [comment]
i'am stupid!!
