### ISSUE TITLE
Question: possible to get PIR/Reed differentiated?

### ISSUE THREAD

**Issue by lexusburn** [PricelessToolkit/MailBoxGuard#53]
I would like to ask, if it's possible to get the events from PIR/Reed differentiated?
As i can see, both sensors will wake up the sensor and then the sensor sends the lora message.
It would be great to get the possibility to differ between PIR and Reed for my use case.

**Comment by PricelessToolkit** [comment]
Unfortunately, this is not possible with the current hardware version.
