### ISSUE TITLE
magnet size for 3d printed case

### ISSUE THREAD

**Issue by tynick** [PricelessToolkit/MailBoxGuard#56]
what magnets are you using for the following file?

`3D/STL/MailBoxGuard_Full_Size_Back_433_868_915.Magnet.stl`

**Comment by PricelessToolkit** [comment]
10x5 but consider using "MailBoxGuard_Full_Size_Back_433_868_915_Magnetic_Open_12x2mm.STL" with 12x4-5mm magnet will stick out 2mm but it will be in direct contact with metal and will hold up much tight.
